name: nadarchitecture
description: You can create a clean structure and benefit from its features
version: 1.0.1
homepage: https://github.com/yusufnadar/nadarchitecture

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_storage: ^2.1.1
  dio: ^5.0.3
  connectivity_plus: ^3.0.3
  json_annotation: ^4.8.0
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
