name: nadarchitecture
description: You can create a clean structure and benefit from its features
version: 0.0.1
homepage: https://github.com/yusufnadar/nadarchitecture

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  json_annotation: ^4.7.0
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  json_serializable: ^6.5.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/icons/png/
    - assets/icons/png/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa/Comfortaa-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700


